package net.bounceme.dur.usenet.swing;

import javax.swing.ListModel;

public class Articles extends javax.swing.JPanel {

    @SuppressWarnings("unchecked")
    public Articles() {
        initComponents();
        articles.setPrototypeCellValue("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        //ListModel myList = new ArticleListModel();
        //articles.setModel(myList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        west = new javax.swing.JScrollPane();
        articles = new javax.swing.JList();
        center = new javax.swing.JScrollPane();
        content = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        articles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        west.setViewportView(articles);

        add(west, java.awt.BorderLayout.WEST);

        center.setViewportView(content);

        add(center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList articles;
    private javax.swing.JScrollPane center;
    private javax.swing.JTextPane content;
    private javax.swing.JScrollPane west;
    // End of variables declaration//GEN-END:variables
}
