/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.bounceme.dur.usenet.swing;

/**
 *
 * @author thufir
 */
public class ButtonBorderLayout extends javax.swing.JPanel {

    /**
     * Creates new form BorderLayout
     */
    public ButtonBorderLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jButton4.setText("jButton4");
        add(jButton4, java.awt.BorderLayout.LINE_END);

        jButton1.setText("jButton1");
        add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setText("jButton2");
        add(jButton2, java.awt.BorderLayout.PAGE_START);

        jButton3.setText("jButton3");
        add(jButton3, java.awt.BorderLayout.PAGE_END);

        jButton5.setText("jButton5");
        add(jButton5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
