/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.bounceme.dur.usenet.swing;

/**
 *
 * @author thufir
 */
public class DatabaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatabaseJPanel
     */
    public DatabaseJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northJPanel = new javax.swing.JPanel();
        center = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        north = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        northJPanel.setLayout(new java.awt.BorderLayout());
        add(northJPanel, java.awt.BorderLayout.CENTER);

        center.setViewportView(jTextPane1);

        add(center, java.awt.BorderLayout.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        north.setViewportView(jTextArea1);

        add(north, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane center;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JScrollPane north;
    private javax.swing.JPanel northJPanel;
    // End of variables declaration//GEN-END:variables
}
