package net.bounceme.dur.usenet.swing;

import java.util.Observable;
import java.util.Observer;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import net.bounceme.dur.usenet.controller.Controller;

public class GroupSelect extends javax.swing.JPanel implements Observer {

    private static final Logger LOG = Logger.getLogger(GroupSelect.class.getName());
        private Controller controller = new Controller();
    private DefaultListModel defaultListModel;

    @SuppressWarnings("unchecked")
    public GroupSelect() {
        defaultListModel = controller.getFolders();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupJList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        groupJList.setModel(defaultListModel);
        groupJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(groupJList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void groupJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupJListValueChanged
        LOG.fine("selected: " + groupJList.getSelectedValue());
        controller.setGroup(groupJList.getSelectedValue().toString());
    }//GEN-LAST:event_groupJListValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList groupJList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
