package net.bounceme.dur.usenet.swing;

import java.util.logging.Logger;
import javax.swing.ListModel;
import net.bounceme.dur.usenet.controller.Controller;
import net.bounceme.dur.usenet.controller.GroupDefaultListModel;

public class GroupSelect extends javax.swing.JPanel {

    private static final Logger LOG = Logger.getLogger(GroupSelect.class.getName());
    private Controller controller = Controller.getInstance();
    private ListModel groups = new GroupDefaultListModel();

    @SuppressWarnings("unchecked")
    public GroupSelect() {
        initComponents();
        groupJList.setModel(groups);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupJList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        groupJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                groupJListMouseReleased(evt);
            }
        });
        groupJList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                groupJListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(groupJList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void groupJListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_groupJListKeyReleased
        userSelectedRow();
    }//GEN-LAST:event_groupJListKeyReleased

    private void groupJListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupJListMouseReleased
        userSelectedRow();
    }//GEN-LAST:event_groupJListMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList groupJList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void userSelectedRow() {
        String folderFullName = groupJList.getSelectedValue().toString();
        controller.setFolderFullName(folderFullName);
        LOG.fine("selected: " + folderFullName);
    }
}
