/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.bounceme.dur.usenet.swing;

/**
 *
 * @author thufir
 */
public class MyTabs extends javax.swing.JPanel {

    /**
     * Creates new form MyTabs
     */
    public MyTabs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        newsgroups1 = new net.bounceme.dur.usenet.swing.Newsgroups();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("tab1", newsgroups1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private net.bounceme.dur.usenet.swing.Newsgroups newsgroups1;
    // End of variables declaration//GEN-END:variables
}
