/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.bounceme.dur.usenet.swing;

/**
 *
 * @author thufir
 */
public class MyTabs extends javax.swing.JPanel {

    /**
     * Creates new form MyTabs
     */
    public MyTabs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        newsgroups = new net.bounceme.dur.usenet.swing.Newsgroups();
        articles = new net.bounceme.dur.usenet.swing.Articles();

        setLayout(new java.awt.BorderLayout());

        tabs.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        newsgroups.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                newsgroupsPropertyChange(evt);
            }
        });
        tabs.addTab("tab1", newsgroups);
        tabs.addTab("tab2", articles);

        add(tabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void newsgroupsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_newsgroupsPropertyChange
        //Newsgroup newsgroup = (Newsgroup) evt.getNewValue();
    }//GEN-LAST:event_newsgroupsPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.bounceme.dur.usenet.swing.Articles articles;
    private net.bounceme.dur.usenet.swing.Newsgroups newsgroups;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
