/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.bounceme.dur.usenet.swing;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.swing.ButtonModel;
import net.bounceme.dur.usenet.controller.Marker;
import net.bounceme.dur.usenet.controller.Persist;
import net.bounceme.dur.usenet.controller.Usenet;

/**
 *
 * @author thufir
 */
public class PanelWithText extends javax.swing.JPanel {

    /**
     * Creates new form PanelWithText
     */
    public PanelWithText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        newNote = new javax.swing.JTextArea();
        addNote = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageJTextPane = new javax.swing.JTextPane();

        newNote.setColumns(20);
        newNote.setRows(5);
        jScrollPane1.setViewportView(newNote);

        addNote.setText("jButton1");
        addNote.setModel(new BtnMdl(new NoteBean()));
        addNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(noteText);

        jScrollPane3.setViewportView(messageJTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(addNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNote, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(218, 218, 218)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteActionPerformed
        BtnMdl buttonModel = (BtnMdl) addNote.getModel();
        NoteBean nb = buttonModel.getMessage();
        String note = newNote.getText();
        nb.setNote(note);
        newNote.setText("");
        Persist p = Persist.INSTANCE;
        p.addNote(nb);
    }//GEN-LAST:event_addNoteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane messageJTextPane;
    private javax.swing.JTextArea newNote;
    private javax.swing.JTextPane noteText;
    // End of variables declaration//GEN-END:variables

    void setJTextArea(String string) {
        newNote.setText(string);
    }

    void setMessages(Marker marker) throws Exception {
        Logger.getLogger(PanelWithText.class.getName()).log(Level.FINE, "hmm ");
        Usenet u = Usenet.INSTANCE;
        List<Message> messages = u.getMessages(marker);
        StringBuilder sb = new StringBuilder();
        for (Message m : messages) {
            try {
                sb.append(m.getSubject().toString());
                sb.append("\n");
            } catch (MessagingException ex) {
                Logger.getLogger(PanelWithText.class.getName()).log(Level.SEVERE, null, ex);
            }
            setJTextArea(sb.toString());
        }
    }

    void setMessage(NoteBean message) {
        messageJTextPane.setText(message.toString());
        addNote.setText(message.toString());
        addNote.setModel(new BtnMdl(message));
    }
}
