package net.bounceme.dur.usenet.swing;

import java.util.logging.Logger;
import net.bounceme.dur.usenet.controller.Controller;

public class PanelWithTabs extends javax.swing.JPanel {

    private static final Logger LOG = Logger.getLogger(PanelWithTabs.class.getName());
    private Controller controller = Controller.getInstance();

    public PanelWithTabs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        groupSelect = new net.bounceme.dur.usenet.swing.GroupSelect();
        articleSelect = new net.bounceme.dur.usenet.swing.ArticleSelect();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("GroupSelect", groupSelect);
        jTabbedPane1.addTab("ArticleList", articleSelect);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("GroupSelect");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.bounceme.dur.usenet.swing.ArticleSelect articleSelect;
    private net.bounceme.dur.usenet.swing.GroupSelect groupSelect;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
