package net.bounceme.dur.usenet.swing;

import java.util.logging.Logger;
import javax.mail.Folder;
import net.bounceme.dur.usenet.controller.MessageBean;

public class PanelWithTabs extends javax.swing.JPanel {

    private static final Logger LOG = Logger.getLogger(PanelWithTabs.class.getName());

    public PanelWithTabs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupArticleDatabase = new javax.swing.JTabbedPane();
        groupSelect = new net.bounceme.dur.usenet.swing.Groups();
        articleSelect = new net.bounceme.dur.usenet.swing.Messages();
        databaseJPanel = new net.bounceme.dur.usenet.swing.Comments();

        setLayout(new java.awt.BorderLayout());

        groupArticleDatabase.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        groupSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                groupSelectPropertyChange(evt);
            }
        });
        groupArticleDatabase.addTab("GroupSelect", groupSelect);

        articleSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                articleSelectPropertyChange(evt);
            }
        });
        groupArticleDatabase.addTab("ArticleList", articleSelect);
        groupArticleDatabase.addTab("Database", databaseJPanel);

        add(groupArticleDatabase, java.awt.BorderLayout.CENTER);
        groupArticleDatabase.getAccessibleContext().setAccessibleName("GroupSelect");
    }// </editor-fold>//GEN-END:initComponents

    private void groupSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_groupSelectPropertyChange
        LOG.fine("property change.." + evt);
        if ("group".equals(evt.getPropertyName())){
            Folder folder = (Folder) evt.getNewValue();
            articleSelect.setFolder(folder);
        }
    }//GEN-LAST:event_groupSelectPropertyChange

    private void articleSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_articleSelectPropertyChange
        if ("messageBean".equals(evt.getPropertyName())){
            MessageBean messageBean = (MessageBean) evt.getNewValue();
            databaseJPanel.setMessageBean(messageBean);
        }
    }//GEN-LAST:event_articleSelectPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.bounceme.dur.usenet.swing.Messages articleSelect;
    private net.bounceme.dur.usenet.swing.Comments databaseJPanel;
    private javax.swing.JTabbedPane groupArticleDatabase;
    private net.bounceme.dur.usenet.swing.Groups groupSelect;
    // End of variables declaration//GEN-END:variables
}
