package net.bounceme.dur.usenet.swing.view;

import java.util.List;
import net.bounceme.dur.usenet.model.MessageBean;
import net.bounceme.dur.usenet.swing.BtnMdl;
import net.bounceme.dur.usenet.swing.Notes;
import net.bounceme.dur.usenet.swing.Persist;
import net.bounceme.dur.usenet.swing.model.NotesTableModel;

public class PanelWithText extends javax.swing.JPanel {

    public PanelWithText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        newNote = new javax.swing.JTextArea();
        addNote = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageJTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        newNote.setColumns(20);
        newNote.setRows(5);
        jScrollPane1.setViewportView(newNote);

        addNote.setText("jButton1");
        addNote.setModel(new BtnMdl(new MessageBean()));
        addNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(messageJTextPane);

        table.setModel(new NotesTableModel());
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(addNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNote, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteActionPerformed
        BtnMdl buttonModel = (BtnMdl) addNote.getModel();
        MessageBean messageBean = buttonModel.getMessage();
        String newNoteText = newNote.getText();
        messageBean.setNote(newNoteText);
        newNote.setText("");
        Persist p = Persist.INSTANCE;
        p.addMessageBean(messageBean);
        setMessage(messageBean);
    }//GEN-LAST:event_addNoteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane messageJTextPane;
    private javax.swing.JTextArea newNote;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    void setJTextArea(String string) {
        newNote.setText(string);
    }

    void setMessage(MessageBean messageBean) {
        messageJTextPane.setText(messageBean.toString());
        addNote.setText(messageBean.toString());
        addNote.setModel(new BtnMdl(messageBean));
        Persist p = Persist.INSTANCE;
        List<Notes> notes = p.getMessages(messageBean);
        NotesTableModel ntm = new NotesTableModel(notes, messageBean);
        table.setModel(ntm);
    }
}
